#!/usr/bin/env python

try:
    from waflib.extras import symwaf2ic
    from waflib.extras.gtest import summary
    # new flow uses calls directly depends()
    recurse = lambda x: None
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)

from waflib import Utils

def load(ctx):
    ctx.load('compiler_cxx')
    ctx.load('boost')
    ctx.load('python')
    ctx.load('pytest')
    ctx.load('post_task')

def depends(ctx):
    ctx('symap2ic', 'src/logging')

def options(opt):
    load(opt)
    recurse(opt)

def configure(cfg):
    load(cfg)
    cfg.check_python_headers()
    cfg.check_boost(lib='python', uselib_store='BOOST4PYLOGGING')
    recurse(cfg)

def build(bld):
    recurse(bld)
    bld(
            target = 'pylogging',
            features = 'cxx cxxshlib pyembed pyext',
            source = 'pylogging.cpp',
            export_includes = '.',
            use = ['BOOST4PYLOGGING', 'logger_obj'],
            cxxflags = ['-Wall', '-Wextra', '-fPIC', '-std=c++11'],
            linkflags = ['-Wl,-zdefs'],
            install_path = '${PREFIX}/lib',
            post_task = 'pyloggingtest',
    )

    bld.install_files(
            '${PREFIX}/bin',
            'pylogging_config_example.py',
            chmod=Utils.O755,
    )

    bld(
        name            = "pyloggingtest",
        tests           = ['test_pylogging.py'],
        features        = 'pytest',
        use             = 'pylogging',
        install_path = '${PREFIX}/bin/tests',
    )
    bld.add_post_fun(summary)
